spring:
  application:
    name: bold-authentic

  datasource:
    url: jdbc:mysql://localhost:3306/bold-authentic?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9000
  servlet:
    context-path: /api/v1

application:
  shopify:
    url : "https://uge0cb-c1.myshopify.com/admin/api/2024-10"
    token : "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"
    location-id : 105039986970

debug: true
